export type DevelopmentType = "web" | "ecommerce" | "app";

export type Development = {
  id: string;
  slug: string;
  title: string;
  domain: string;
  url: string;
  type: DevelopmentType;
  technology: string;
  image: string;
  /** Posición relativa para el cable (porcentaje del contenedor) */
  cableX: number;
  cableY: number;
  /** Color RGB "r,g,b" para acento */
  accentRgb: string;
  /** Descripción del proyecto (placeholder por ahora) */
  description?: string;
};

export const DEVELOPMENTS: Development[] = [
  {
    id: "dev-1",
    slug: "kinesiologia-y-salud",
    title: "Kinesiología y Salud",
    domain: "kinesiologiaysalud.com",
    url: "https://kinesiologiaysalud.com",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768397026/kinesioysalud_1_qhmym6.webp",
    cableX: 50,
    cableY: 90,
    accentRgb: "132,185,237",
    description: "Sitio web desarrollado con React para un centro de kinesiología y salud. Incluye información sobre servicios, profesionales y contacto.",
  },
  {
    id: "dev-2",
    slug: "amo-mi-casa",
    title: "Amo mi casa",
    domain: "amomicasahome.com",
    url: "https://amomicasahome.com",
    type: "ecommerce",
    technology: "Next.js",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1769297795/amo-mi-casa_qwg5tb_1_1_fxfgxf.webp",
    cableX: 20,
    cableY: 85,
    accentRgb: "38,59,119",
    description: "Plataforma de e-commerce desarrollada con Next.js para la venta de productos para el hogar. Incluye carrito de compras, gestión de pedidos y pasarela de pagos.",
  },
  {
    id: "dev-3",
    slug: "pedri",
    title: "Pedri",
    domain: "app.pedriapp.com",
    url: "https://app.pedriapp.com",
    type: "app",
    technology: "Next.js",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768398036/pedri_czzsak.webp",
    cableX: 80,
    cableY: 85,
    accentRgb: "80,124,201",
    description: "Aplicación web desarrollada con Next.js. Plataforma completa con funcionalidades avanzadas y diseño moderno.",
  },
  {
    id: "dev-4",
    slug: "salud-dental",
    title: "Salud Dental",
    domain: "odontologiajgoroso.com",
    url: "https://odontologiajgoroso.com/",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768398451/jesica_1_dvkreb.webp",
    cableX: 35,
    cableY: 90,
    accentRgb: "132,185,237",
    description: "Sitio web para consultorio odontológico desarrollado con React. Presenta servicios, información sobre tratamientos y sistema de turnos.",
  },
  {
    id: "dev-5",
    slug: "natalia-domecq",
    title: "Lic. Natalia Domecq",
    domain: "psicodomecq.com",
    url: "https://psicodomecq.com",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768400848/natalia_xqpuen.webp",
    cableX: 65,
    cableY: 90,
    accentRgb: "132,185,237",
    description: "Sitio web profesional para psicóloga desarrollado con React. Incluye información sobre servicios, enfoque terapéutico y contacto.",
  },
  {
    id: "dev-6",
    slug: "nutricion-integral",
    title: "Nutrición Integral",
    domain: "mvnutricionconsciente.com",
    url: "https://mvnutricionconsciente.com",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768402054/maria_wxw23y.webp",
    cableX: 15,
    cableY: 90,
    accentRgb: "132,185,237",
    description: "Sitio web para nutricionista desarrollado con React. Presenta servicios de consultoría nutricional, planes alimentarios y contacto.",
  },
  {
    id: "dev-andrea-cohen",
    slug: "andrea-cohen",
    title: "Lic. Andrea Cohen",
    domain: "andreacohennutricionista.com",
    url: "https://lic-andrea-cohen-nutricionista.vercel.app",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768407494/Captura_de_pantalla_413_byhtvk.webp",
    cableX: 25,
    cableY: 90,
    accentRgb: "132,185,237",
    description: "Sitio web profesional para nutricionista desarrollado con React. Incluye información sobre servicios, metodología y contacto.",
  },
  {
    id: "dev-7",
    slug: "estudio-juridico",
    title: "Estudio Jurídico",
    domain: "ezequielabogado.com",
    url: "https://ezequiel-cortes-abogado.vercel.app/",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768402491/ezequiel_wgolbc.webp",
    cableX: 50,
    cableY: 85,
    accentRgb: "132,185,237",
    description: "Sitio web para estudio jurídico desarrollado con React. Presenta áreas de práctica, información profesional y contacto.",
  },
  {
    id: "dev-tuturno",
    slug: "tu-turno-barberia",
    title: "Tu Turno Barbería",
    domain: "tuturnobarberia.com",
    url: "https://tu-turno-jet.vercel.app",
    type: "app",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768422963/Captura_de_pantalla_416_fyohyw.webp",
    cableX: 50,
    cableY: 85,
    accentRgb: "80,124,201",
    description: "Aplicación web para gestión de turnos de barbería desarrollada con React. Permite a los clientes reservar turnos y gestionar citas.",
  },
  {
    id: "dev-8",
    slug: "pablo-perez",
    title: "Lic. Pablo Pérez",
    domain: "pabloperezkinesiologia.com",
    url: "https://lic-pablo-perez.vercel.app",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768407201/pablo_perez_ozno0c.webp",
    cableX: 80,
    cableY: 90,
    accentRgb: "132,185,237",
    description: "Sitio web para kinesiólogo desarrollado con React. Incluye información sobre servicios, especialidades y contacto.",
  },
  {
    id: "dev-peliculas",
    slug: "tienda-peliculas",
    title: "Tienda de Películas",
    domain: "bibliotecapeliculas.com",
    url: "https://biblioteca-peliculas-ywrn.vercel.app/",
    type: "app",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768424107/Captura_de_pantalla_417_xteyjt.webp",
    cableX: 70,
    cableY: 85,
    accentRgb: "80,124,201",
    description: "Aplicación web para catálogo de películas desarrollada con React. Permite buscar, filtrar y explorar una biblioteca de películas.",
  },
  {
    id: "dev-13",
    slug: "aaci",
    title: "AACI",
    domain: "aaci.com",
    url: "https://aaci.vercel.app/",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768403016/aaci_xkz9sg.webp",
    cableX: 15,
    cableY: 90,
    accentRgb: "132,185,237",
    description: "Sitio web institucional desarrollado con React. Presenta información sobre la organización, actividades y contacto.",
  },
  {
    id: "dev-9",
    slug: "a-mar-salud",
    title: "A-Mar Salud",
    domain: "amarsalud.com",
    url: "https://a-mar-salud.vercel.app",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768403276/a-marSalud_npy0iz.webp",
    cableX: 20,
    cableY: 90,
    accentRgb: "132,185,237",
    description: "Sitio web para centro de salud desarrollado con React. Presenta servicios médicos, profesionales y información de contacto.",
  },
  {
    id: "dev-10",
    slug: "eukinesia",
    title: "Eukinesia",
    domain: "eukinesia.com",
    url: "https://eukinesiakinesiologia.vercel.app/",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768403724/eukinesia_qmblft.webp",
    cableX: 65,
    cableY: 85,
    accentRgb: "132,185,237",
    description: "Sitio web para centro de kinesiología desarrollado con React. Incluye información sobre tratamientos, profesionales y contacto.",
  },
  {
    id: "dev-11",
    slug: "crs-informatica",
    title: "CRS Informática",
    domain: "crsinformatica.com",
    url: "https://crsinformaticapc.vercel.app",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768404579/crsinformatica_fgptjr.webp",
    cableX: 35,
    cableY: 85,
    accentRgb: "132,185,237",
    description: "Sitio web para empresa de informática desarrollado con React. Presenta servicios tecnológicos, soluciones y contacto.",
  },
  {
    id: "dev-12",
    slug: "wanda-perrin",
    title: "Lic. Wanda Perrin",
    domain: "wandakinesiologia.com",
    url: "https://lic-wanda-perrin-kinesiologia.vercel.app/",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768405888/Captura_de_pantalla_411_u8phlz.webp",
    cableX: 50,
    cableY: 90,
    accentRgb: "132,185,237",
    description: "Sitio web para kinesióloga desarrollado con React. Incluye información sobre servicios, especialidades y contacto.",
  },
  {
    id: "dev-internet-retro",
    slug: "internet-retro",
    title: "Internet Retro",
    domain: "internet-retro.com",
    url: "https://internet-retro.vercel.app",
    type: "app",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768424523/Captura_de_pantalla_418_pqeuvd.webp",
    cableX: 60,
    cableY: 85,
    accentRgb: "80,124,201",
    description: "Aplicación web con diseño retro desarrollada con React. Experiencia nostálgica con estética de los años 90.",
  },
  {
    id: "dev-14",
    slug: "victoria-nazra",
    title: "Lic. Victoria Nazra",
    domain: "victorianazrapsicologa.com",
    url: "https://victoria-psicologa.vercel.app/",
    type: "web",
    technology: "React",
    image: "https://res.cloudinary.com/dzoupwn0e/image/upload/v1768408990/victoria_hpxsnn.webp",
    cableX: 80,
    cableY: 90,
    accentRgb: "132,185,237",
    description: "Sitio web para psicóloga desarrollado con React. Incluye información sobre servicios, enfoque terapéutico y contacto.",
  },
];

export function getDevelopmentById(id: string): Development | null {
  return DEVELOPMENTS.find((dev) => dev.id === id) ?? null;
}

export function getDevelopmentBySlug(slug: string): Development | null {
  return DEVELOPMENTS.find((dev) => dev.slug === slug) ?? null;
}

export function getAllDevelopments(): Development[] {
  return DEVELOPMENTS;
}
